export const catelogue = [
  {
    id: 1,
    categoryImage: "/images/headphone1.svg",
    title: "JBL Live 660NC",
    price: "$579.99",
    mainPrice: "$600.00",
    rating: 4.9,
  },
  {
    id: 2,
    categoryImage: "/images/headphone2.svg",
    title: "Sony WH-1000XM4",
    price: "$239.99",
    mainPrice: "$250.00",
    rating: 4.9,
  },
  {
    id: 3,
    categoryImage: "/images/headphone1.svg",
    title: "JBL Live 660NC",
    price: "$579.99",
    mainPrice: "$600.00",
    rating: 4.9,
  },
  {
    id: 4,
    categoryImage: "/images/headphone2.svg",
    title: "Airpods Max",
    price: "$579.99",
    mainPrice: "$600.00",
    rating: 4.9,
  },
  {
    id: 5,
    categoryImage: "/images/headphone1.svg",
    title: "JBL Live 660NC",
    price: "$579.99",
    mainPrice: "$600.00",
    rating: 4.9,
  },
  {
    id: 6,
    categoryImage: "/images/headphone2.svg",
    title: "Airpods Max",
    price: "$579.99",
    mainPrice: "$600.00",
    rating: 4.9,
  },
  {
    id: 7,
    categoryImage: "/images/headphone1.svg",
    title: "JBL Live 660NC",
    price: "$579.99",
    mainPrice: "$600.00",
    rating: 4.9,
  },
  {
    id: 8,
    categoryImage: "/images/headphone2.svg",
    title: "Airpods Max",
    price: "$579.99",
    mainPrice: "$600.00",
    rating: 4.9,
  },
];
